module.exports = {

	COLOR_REQ: "Color is required",
	EMAIL_REQ: "Please enter your email address.",
	EMAIL_EXISTS: "This email address is already registered.",
	IMAGE_IS_REQ: "Image is required.",
	LOGIN_SUCC: "Login successfully.",
	MSG_REQ: "Message is required",
	ORDER_ADDED: "Your order was successfully sent!",
	MISSING_PARAMS: "Missing params.",
	ORDER_FETCHED: "order fetched successfully.",
	MESSAGE_REQ: "Please add message for users.",
	MISSING_PARAMETER: "Parameter is missing",
	NEW_PASS_REQ: "Please enter New password.",
	NO_ADMIN_FND: "Admin not found.",
	NAME_REQ: "name is required.",
	ORDER_DELETED: "Order Deleted Successfully",
	ORDER_CODE_REQ:"Order code is required",
	ORDER_NOT_FND: "Order not found",
	QUANTITY_REQ: "Quantity is required.",
	REQUIRED_DATE:"Required date is required",
	SOMETHING_WRONG: "Something Went Wrong!",
	SUCC: "Successfully done.",
	SIZE_IS_REQ: "Product size is required.",
	TYPE_REQ: "Type is required.",
	TOKEN_REQ: "token is required.",
	USER_DETAILS: "User Details",
	USER_CREATED: "User created",
	USER_UPDATED: "Profile updated successfully.",
	UPDT_PROFILE_SUCC: 'Profile updated successfully.',
	USER_NOT_FOUND: "User not found",
	USER_ID: "User Id is required.",
	USER_ACTIVE: "User activated successfully.",
	USER_LIST: "Users list.",
	USER_INACTIVE: "User inactived successfully",
	UNAUTH_ERR: "You are not authorized to acceess this request.",
	UNAUTH_ADMIN: "Unauthorized admin",
};
